# Generated by Django 4.1.7 on 2023-03-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('saturated_fat', models.FloatField(blank=True, null=True)),
                ('unsaturated_fat', models.FloatField(blank=True, null=True)),
                ('trans_fat', models.FloatField(blank=True, null=True)),
                ('carbs', models.FloatField(blank=True, null=True)),
                ('protein', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='nutriScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('score', models.CharField(max_length=20)),
            ],
        ),
    ]
