# Generated by Django 4.1.7 on 2023-03-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BetterCart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='calories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='carbs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='protein',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='saturated_fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='trans_fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='unsaturated_fat',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
